name: Monthly Workflow

on:
  schedule:
    - cron: "0 0 1 * *"

env:
  #############################
  ########## EGYPT ############
  #############################
  
  # Dev env variables
  ECR_REPOSITORY                        : 'rabbitmart-stg/os-osrm-backend'
  NAMESPACE_DEV                             : 'backend-dev'


jobs:
  run-monthly-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout helm
        uses: actions/checkout@v4
        with:
          repository: 'Rabbit-Mart/sre-installed-helm-charts-and-k8s-manifests.git'
          ref       : "main"
          token     : ${{ secrets.TOKEN_GITHUB }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id    : ${{ env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region           : eu-west-1

      - name: Login to Amazon ECR
        id:   login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      steps:
    - name: set env variables
      shell: bash
      run: |
            echo "ECR_REPOSITORY=$(echo $ECR_REPOSITORY)" >> $GITHUB_ENV
            echo "NAMESPACE=$(echo $NAMESPACE_PROD)" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=$(echo ${{ secrets.AWS_ACCESS_KEY_ID_PROD }} )" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=$(echo ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }} )" >> $GITHUB_ENV
            echo "EKS_CLUSTER=$(echo ${{ secrets.EKS_CLUSTER_PROD }} )" >> $GITHUB_ENV

      - name: Run a script
        env:
          ECR_REGISTRY : ${{ steps.login-ecr.outputs.registry }}
        run: |
            echo "Deploying EGY OSRM-STG"
            cd environments/stg/osrm/egy
            DOCKER_BUILDKIT=1 docker build --target production --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            
